### Product create 

POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "test name",
  "price": "test price",
  "image_url": "test image_url",
  "description": "test description"
  
}

### Product show

GET http://localhost:3000/products


### Product index

GET http://localhost:3000/products


### Product update 

PATCH http://localhost:3000/products/6
Content-Type: application/json

{
  "name": "Orange",
  "price": "2",
  "image_url": "test image_url",
  "description": "test description"
  
}