@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTA1ODQzODJ9.fRZ95uQYycOjPieQ2KrPmiJI6w6IyKbSc5ziA2GfGZ8

### Carted Product Delete

DELETE http://localhost:3000/carted_products/1
Authorization: Bearer {{jwt}}


### Carted Products Show

GET http://localhost:3000/carted_products/
Authorization: Bearer {{jwt}} 

### Carted Products Index

GET http://localhost:3000/carted_products/
Authorization: Bearer {{jwt}}

### Carted Products Create

POST http://localhost:3000/carted_products
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "user_id": "1",
  "product_id": "3",
  "quantity": "2",
  "status": "carted",
  "order_id": "1"
}


### Orders Create
POST http://localhost:3000/orders
Authorization: Bearer {{jwt}}
Content-Type: application/json


### Orders Show

GET http://localhost:3000/orders/
Authorization: Bearer {{jwt}}

### Order Index

GET http://localhost:3000/orders/1
Authorization: Bearer {{jwt}}



### Product create 

POST http://localhost:3000/products
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "Coconut",
  "price": "4",
  "description": "This is a fruit",
  "supplier_id": "2"
}

### Product show

GET http://localhost:3000/products/3


### Product index

GET http://localhost:3000/products
Authorization: Bearer {{jwt}}


### Supplier index 

GET http://localhost:3000/suppliers


### Images index

GET http://localhost:3000/images


### Product update 

PATCH http://localhost:3000/products/6
Content-Type: application/json

{
  "name": "Orange",
  "price": "2",
  "image_url": "test image_url",
  "description": "test description"
  
}

### Product destroy

DELETE http://localhost:3000/products/5


### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Charlie Chaplin",
  "email": "chaplin@test.com",
  "password": "password1",
  "password_confirmation": "password1"
}


### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "chaplin@test.com",
  "password": "password1"
}

